# for Linux
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-pc-windows-msvc]
linker = "lld"
rustflags = [
  "-Lnative=/home/johnchen1229/.xwin/crt/lib/x86_64",
  "-Lnative=/home/johnchen1229/.xwin/sdk/lib/um/x86_64",
  "-Lnative=/home/johnchen1229/.xwin/sdk/lib/ucrt/x86_64"
]
